version: '3.8'
services:
  mongodb:
    image: registry.semaphoreci.com/mongo:4.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  flasksemaphore:
    image: pyflasksemaphore
    container_name: semaphore-pyflask-docker_flasksemaphore_1
    build:
      context: .
      dockerfile: ./flask.Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - .:/opt/
    environment:
      - DB=mongodb://mongodb:27017/tasks
      - PORT=5000
    depends_on:
      - mongodb
